name: Update Credly Badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Atualizar badges do Credly
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: diego-rondao
          NUMBER_LAST_BADGES: 0